"""empty message

Revision ID: ca27cac04831
Revises: 2c7f3c256a27
Create Date: 2019-10-04 10:57:46.362155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca27cac04831'
down_revision = '2c7f3c256a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_archived')
    # ### end Alembic commands ###
